import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { lazy, useMemo } from "react";
import ToastProvider from "@/components/ToastProvider";
import Background from "@/components/Background";
import React from "react";

// const ParticlesContainer = lazy(
//   () => import("../components/ParticlesContainer")
// );

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avinash Kumar- Frontend developer",
  description: "Generated by Avinash Kr Yadav",
  generator: "Next.js",
  manifest: "manifest.json",
  keywords: [
    "nextjs",
    "nextjs13",
    "next13",
    "pwa",
    "next-pwa",
    "portfolio",
    "nextjsapprouting",
    "nextjsAppRouter",
  ],
  // themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#000" }],
  authors: [
    { name: "Avinash Kumar Yadav" },
    {
      name: "Avinash Kumar Yadav",
      url: "https://www.linkedin.com/in/avinashydv/",
    },
  ],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: "/icon-128x128.png" },
    { rel: "icon", url: "/icon-128x128.png" },
  ],
};

const MemoizedBackground = React.memo(Background);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const backgroundComponent = useMemo(() => <MemoizedBackground />, []);

  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        {backgroundComponent}
        <ToastProvider />
        <Header />

        {/* <Nav /> */}
        {children}
        {/* <ParticlesContainer /> */}

        <Footer />
      </body>
    </html>
  );
}
