import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { lazy } from "react";

const ParticlesContainer = lazy(
  () => import("../components/ParticlesContainer")
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avinash Kumar- Frontend developer",
  description: "Generated by Avinash Kr Yadav",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <Nav /> */}
        {children}
      </body>
      <ParticlesContainer />
      <Footer />
    </html>
  );
}
